spring:
  datasource:
    url: jdbc:mysql://193.112.44.236:3306/blogs?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456789
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    property-naming-strategy: SNAKE_CASE
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false