spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456789
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    property-naming-strategy: SNAKE_CASE